# Generated by Django 3.0.5 on 2020-07-04 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20200704_1607'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='hunter',
        ),
    ]
